app = "anr-ggp-faucet"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []


[[services]]
protocol = "tcp"
internal_port = 8000

[[services.ports]]
handlers = ["http"]
port = "80"
force_https = true

[[services.ports]]
handlers = ["http", "tls"]
port = "443"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.tcp_checks]]
grace_period = "30s"
interval = "30s"
restart_limit = 0
timeout = "5s"
